# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ds-build-and-test

on:
  push:
  pull_request:

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  SRC_DIR: .

  AZURE_APP_PACKAGE_PATH: .\DelegationStation\published
  AZURE_APP_PKG_NAME: webapp

  AZURE_UPDATE_FUNCTION_PACKAGE_PATH: .\UpdateDevices\published
  AZURE_UPDATE_FUNCTION_PKG_NAME: update-function

  AZURE_WEBJOB_PACKAGE_PATH: .\WhiteSpaceCleaner\published
  AZURE_WEBJOB_PKG_NAME: webjob

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        dotnet build ${{ env.SRC_DIR }}/DelegationSharedLibrary --configuration ${{ env.CONFIGURATION}} --no-restore
        dotnet build ${{ env.SRC_DIR }}/DelegationStation --configuration ${{ env.CONFIGURATION}} --no-restore
        dotnet build ${{ env.SRC_DIR }}/UpdateDevices --configuration ${{ env.CONFIGURATION}} --no-restore
        dotnet build ${{ env.SRC_DIR }}/WhiteSpaceCleaner --configuration ${{ env.CONFIGURATION}} --no-restore
        # dotnet build ${{ env.SRC_DIR }}/DelegationStationTests --configuration ${{ env.CONFIGURATION}} --no-restore

    - name: Publish
      run: |
        dotnet publish ${{ env.SRC_DIR }}/DelegationStation --configuration ${{ env.CONFIGURATION}} --no-build --output "${{ env.AZURE_APP_PACKAGE_PATH }}"
        dotnet publish ${{ env.SRC_DIR }}/WhiteSpaceCleaner --configuration ${{ env.CONFIGURATION}} --no-build --output "${{ env.AZURE_WEBJOB_PACKAGE_PATH }}"
        dotnet publish ${{ env.SRC_DIR }}/UpdateDevices --configuration ${{ env.CONFIGURATION}} --no-build --output "${{ env.AZURE_UPDATE_FUNCTION_PACKAGE_PATH }}"
      
    - name: Upload WebApp Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.AZURE_APP_PKG_NAME }}
        path: ${{ env.AZURE_APP_PACKAGE_PATH }}

    - name: Upload WebJob Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.AZURE_WEBJOB_PKG_NAME }}
        path: ${{ env.AZURE_WEBJOB_PACKAGE_PATH }}

    - name: Upload Update Function Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.AZURE_UPDATE_FUNCTION_PKG_NAME }}
        path: ${{ env.AZURE_UPDATE_FUNCTION_PACKAGE_PATH }}
